# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pict',
            new_name='profile_pic',
        ),
    ]
